project_id = "lwhqguoczgutntjahypu"

[functions.send-expiration-report]
verify_jwt = true

[functions.send-whatsapp-report]
verify_jwt = true

[functions.get-tiny-products]
verify_jwt = false

[functions.sync-tiny-stock]
verify_jwt = false

[functions.compare-tiny-stock]
verify_jwt = false

[functions.j3-create-order]
verify_jwt = false

[functions.j3-get-label]
verify_jwt = false

[functions.j3-get-history]
verify_jwt = false

[functions.j3-check-coverage]
verify_jwt = false

[functions.update-tiny-description]
verify_jwt = false
