project_id = "lwhqguoczgutntjahypu"

[functions.send-expiration-report]
verify_jwt = true

[functions.send-whatsapp-report]
verify_jwt = true

[functions.get-tiny-products]
verify_jwt = false

[functions.sync-tiny-stock]
verify_jwt = false
